scale: 2
fit:
- 1
1:
  pose:
  - 60
  - 120
  - 20
  - 0
  - 0.1
  - 1.8
objects:
  bluerov:
    center:
    - 10.0
    - 3.0
    - -8.0
    - -0.19999999999999998
    - -0.19999999999999996
    - -7.080022991082185e-18
    file: /home/olivier/code/ros2/install/marine_presenter/share/marine_presenter/objects/urdf/bluerov.xacro
    roll: 0.0
    rx: 1.0
    ry: 3.5
    slide: 14
    t: 30
  turbine:
    center:
    - 10
    - -15
    - -7
    - 0
    - 0
    - 1.571
    file: /home/olivier/code/ros2/install/marine_presenter/share/marine_presenter/objects/urdf/turbine.xacro
    joints:
    - -3
  yacht:
    center:
    - 71.0
    - -1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.6
    file: /home/olivier/code/ros2/install/marine_presenter/share/marine_presenter/objects/urdf/yacht.xacro
    roll: -0.4
    rx: 0.5
    ry: 2.9
    slide: 18
    t: -20
2:
  pose: &id002
  - -10
  - 0
  - 2
  - 0
  - 0
  - 1
14:
  pose: &id001
  - 10
  - 3
  - -8
  - 0
  - -0.2
  - 0
15:
  pose: *id001
  video: /home/olivier/code/ros2/src/marine_presenter/example/video.mp4
17:
  pose: *id001
  video: /home/olivier/code/ros2/src/marine_presenter/example/video.mp4
18:
  pose: &id003
  - 71
  - -1
  - 2
  - 0
  - 0
  - 0.6
pdf_time: 1642522868
slides: 19
cam_pose:
- 1
- 0
- 2
- 0
- 0
- 0
3:
  pose: *id002
4:
  pose: *id002
5:
  pose: *id002
6:
  pose: *id002
7:
  pose: *id002
8:
  pose: *id002
9:
  pose: *id002
10:
  pose: *id002
11:
  pose: *id002
12:
  pose: *id002
13:
  pose: *id002
16:
  pose: *id001
19:
  pose: *id003
